CREATE TABLE IF NOT EXISTS students (
  id SERIAL PRIMARY KEY,
  nim VARCHAR(255) NOT NULL UNIQUE,
  nama VARCHAR(255) NOT NULL,
  grade INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);